// <auto-generated />
using System;
using Assignment.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment.API.Migrations
{
    [DbContext(typeof(DALDbContext))]
    partial class DALDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment.API.Models.CategoryModel", b =>
                {
                    b.Property<int>("category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("creation_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastmodificationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("category_Id");

                    b.ToTable("categoryModels");
                });

            modelBuilder.Entity("Assignment.API.Models.ChapterModel", b =>
                {
                    b.Property<int>("chapter_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentType")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("creation_Time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("deletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("lastmodificationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("publishedDatetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("chapter_Id");

                    b.ToTable("chapterModels");
                });

            modelBuilder.Entity("Assignment.API.Models.MappingModel", b =>
                {
                    b.Property<int>("map_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<int>("chapter_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("creationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("creatorUserId")
                        .HasColumnType("int");

                    b.HasKey("map_Id");

                    b.ToTable("mappingModels");
                });
#pragma warning restore 612, 618
        }
    }
}
